# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get to Directory
      run: cd ${GITHUB_WORKSPACE}
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
 # adding on
  runTests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8]
    steps: # may need to edit and add -DnondexRuns=10 or -DnondexRuns=100
    - name: Check maven
      run: mvn --version
    - name: Clean Install
      run: mvn clean install
    - name: Compile the module
      run:  mvn test-compile -pl apollo-biz -am
    - name: Run tests without nondex
      run: mvn -pl apollo-biz test -Dtest=com.ctrip.framework.apollo.biz.service.NamespaceBranchServiceTest#testUpdateBranchGrayRulesWithUpdateOnce  
    - name: Run tests with nondex shuffle
      run: mvn -pl apollo-biz edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.ctrip.framework.apollo.biz.service.NamespaceBranchServiceTest#testUpdateBranchGrayRulesWithUpdateOnce        
